# Generated by Django 4.2.1 on 2023-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EEGDatabaseAPI', '0002_subject_timeserie_run_timeserie_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeserie',
            name='trial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
