# Generated by Django 4.2.1 on 2023-05-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EEGDatabaseAPI', '0003_alter_timeserie_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeserie',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EEGDatabaseAPI.classes'),
        ),
    ]
