# Generated by Django 4.2.1 on 2023-05-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EEGDatabaseAPI', '0005_alter_timeserie_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeserie',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EEGDatabaseAPI.classes'),
        ),
    ]
