# Generated by Django 4.2.1 on 2023-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EEGDatabaseAPI', '0008_alter_timeserie_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeserie',
            old_name='class_id',
            new_name='label',
        ),
    ]
