# Generated by Django 4.2.1 on 2023-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EEGDatabaseAPI', '0010_rename_label_timeserie_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='class_id'),
        ),
    ]
